[build-system]
requires = ["meson-python", "ninja", "meson"]
build-backend = "mesonpy"

[project]
name = "vsfgs"
version = "0.3.0"
description = "VapourSynth Film Grain Synthesis Plugin using dav1d"
authors = [
    { name = "PingWer74" }
]
requires-python = ">=3.13"
dependencies = [
    "vapoursynth>=74"
]

[project.optional-dependencies]
dev = ["pytest"]

[tool.meson-python]
allow-windows-internal-shared-libs = true
